
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __sample__
#define __sample__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
    class sample;
}

class sample : public ::java::lang::Object
{

public:
  sample();
  virtual void myNative(::java::lang::String *);
  virtual void myJava(::java::lang::String *);
  static void main(JArray< ::java::lang::String * > *);
  static ::java::lang::Class class$;
};

#endif // __sample__
